[build]
builder = "nixpacks"

[deploy]
startCommand = "bash start.sh"
restartPolicyType = "always"

# Persistent volume for database and cache files
[[deploy.volumes]]
mountPath = "/app/data"
name = "lemegeton-data"